# Publishes a composer package and deploys documentation
# See https://git.luminfire.net/templates/gitlab/ci-templates/-/tree/master/composer-package
# See also https://git.luminfire.net/templates/gitlab/ci-templates/-/tree/master/wp-plugin
#
# See also:
# - https://docs.gitlab.com/ee/user/packages/
# - https://docs.gitlab.com/13.2/ee/user/packages/composer_repository/index.html
# - https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Composer.gitlab-ci.yml

stages:
  - test
  - build
  - deploy

cache:
  key: $CI_BUILD_REF_NAME
  paths:
    - .npm
    - node_modules
    - public
    - vendor

include:
  - project: 'templates/gitlab/ci-templates'
    file:
      - 'build/composer-package.yml'
      - 'test/phpunit.yml'

test:unit-tests:
  tags:
    - docker
  image: edbizarro/gitlab-ci-pipeline-php:8.0-fpm
  before_script:
    - composer config http-basic.git.luminfire.net ___token___ "$PERSONAL_ACCESS_TOKEN"
