# Publishes a composer package and deploys documentation
# See https://git.luminfire.net/ops/tooling/ci/gitlab-ci-general/-/tree/master/composer-package
# See also https://git.luminfire.net/ops/tooling/ci/gitlab-ci-general/-/tree/master/wp-plugin
#
# See also:
# - https://docs.gitlab.com/ee/user/packages/
# - https://docs.gitlab.com/13.2/ee/user/packages/composer_repository/index.html
# - https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Composer.gitlab-ci.yml

stages:
  - test
  - build
  - deploy

cache:
  key: $CI_BUILD_REF_NAME
  paths:
    - .npm
    - node_modules
    - public
    - vendor

include:
  - project: 'ops/tooling/ci/gitlab-ci-templates'
    file:
      - 'build/composer-package.yml'

test:phpn_unit:
  stage: test
  resource_group: test
  tags:
    - docker
  image: edbizarro/gitlab-ci-pipeline-php:8.0-fpm
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
  interruptible: true

